<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="game_tests.TestGame-20231217143229" tests="2" file="game_tests.py" time="0.032" timestamp="2023-12-17T14:32:30" failures="0" errors="1" skipped="0">
	<testcase classname="game_tests.TestGame" name="test_run_game" time="0.023" timestamp="2023-12-17T14:32:30"/>
	<testcase classname="game_tests.TestGame" name="test_run_round" time="0.009" timestamp="2023-12-17T14:32:30">
		<error type="AttributeError" message="'NoneType' object has no attribute 'symbol'"><![CDATA[Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "c:\users\pavik\code\ea6 bui_ci\src\unittest\python\game_tests.py", line 16, in test_run_round
    game.run_round(game.computer)
    ^^^^^^^^^^^^^^^^^
  File "c:\users\pavik\code\ea6 bui_ci\src\main\python\game.py", line 47, in run_round
    player.make_move(self.board, self.round)
    ^^^^^^^^^^^^^^^^^
  File "c:\users\pavik\code\ea6 bui_ci\src\main\python\player.py", line 105, in make_move
    self.make_second_move(board)
    ^^^^^^^^^^^^^^^^^
  File "c:\users\pavik\code\ea6 bui_ci\src\main\python\player.py", line 120, in make_second_move
    if board.game_grid[1][1] == self.opponent.symbol:
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'symbol'
]]></error>
	</testcase>
</testsuite>
